### ISSUE TITLE
colored segmentation to gray class value png

### ISSUE THREAD

**Issue by ahundt** [warmspringwinds/tf-image-segmentation#18]
You mentioned there is a more efficient function for converting the colored segmentation pngs to gray class pngs where the value is the class number. Which is the preferred function to do this?

**Comment by warmspringwinds** [comment]
We read the png file in the following way:
https://github.com/warmspringwinds/tf-image-segmentation/blob/master/tf_image_segmentation/utils/tf_records.py#L37

This give you the classes and not the rgb values

**Comment by ahundt** [comment]
Thanks!
