### ISSUE TITLE
tensorflow 1.1 and tensorflow/models workarounds

### ISSUE THREAD

**Issue by ahundt** [warmspringwinds/tf-image-segmentation#20]
If you're running resnet with the latest tensorflow and tensorflow/models you will need the following:
https://github.com/tensorflow/models/pull/1447

I plan to update this with additional info for running on tensorflow 1.1

**Comment by BrianOn99** [comment]
With this commit, should we specify `spatial_squeeze=False` in `tf_image_segmentation/models/resnet_v1_101_8s.py`?

**Comment by ahundt** [comment]
They've merged the fix. Yes `spatial_squeeze=False` because that would reduce the number of output dimensions and we are making predictions with the same dimensions as the input.
