### ISSUE TITLE
Realtime image segmentation

### ISSUE THREAD

**Issue by ghost** [warmspringwinds/tf-image-segmentation#26]
Daniil, your tensorFlow project is great for search human on images. Thanks for it! Let me introduce myself - Artyom, russian developer. And i want to ask you: is it possible to create tensorflow realisation with realtime detection from video? (like your cut a human from photo). Even on powerfull servers one image processing too slow for realtime project.

**Comment by warmspringwinds** [comment]
Hi,

Did you use enable GPU on your machine?

You can also use smaller network like Resnet-18 or Resnet-34.
It is available here:
https://github.com/warmspringwinds/dense-ai

**Comment by warmspringwinds** [comment]
@WanteevNinja Have a look at this -- I ran it on a web cam:
https://github.com/warmspringwinds/pytorch-cpp#demos

**Comment by ghost** [comment]
Thanks!

чт, 28 дек. 2017 г., 0:47 Daniil Pakhomov <notifications@github.com>:
