### ISSUE TITLE
Where is the checkpoint file?

### ISSUE THREAD

**Issue by LiyaoTang** [warmspringwinds/tf-image-segmentation#41]
When importing the trained model, I got an error of .ckpt file not found. And actually the trained model seems not on the github. 

May I ask where coud we download the trained model?

**Comment by sumedhvdatar** [comment]
Yes can someone please tell out of 3 files,which is the ckpt file.

**Comment by EvilPerfectionist** [comment]
Hi, please change 'model_fcn8s_final.ckpt' to 'model_'fcn8s_final.ckpt.index' or 'fcn8s_final.ckpt.meta'. These files can be downloaded from 'https://github.com/warmspringwinds/tf-image-segmentation' where please try to find 'Model Download Link'. Good Luck! @beihaifusang
