### ISSUE TITLE
Are forked repositories required? What commits to use?

### ISSUE THREAD

**Issue by ahundt** [warmspringwinds/tf-image-segmentation#5]
Is semantic segmentation not possible with this repository and upstream tensorflow and tensorflow/models alone [as detailed in your comment](https://github.com/warmspringwinds/tf-image-segmentation/blob/master/tf_image_segmentation/models/fcn_32s.py#L104)?

It seems that, for example, upstream tensorflow/models [vgg](https://github.com/tensorflow/models/blob/master/slim/nets/vgg.py) doesn't contain the parameter [fc_conv_padding](https://github.com/warmspringwinds/tf-image-segmentation/blob/master/tf_image_segmentation/models/fcn_32s.py#L112).

If specific forks/commits are needed, which ones should I use?

**Comment by warmspringwinds** [comment]
Hi,

We have mentioned it here:
https://github.com/warmspringwinds/tf-image-segmentation#installation

Basically, you need a custom ```tensorflow/models``` fork.

**Comment by ahundt** [comment]
I don't think this branch exists:

`git clone -b fully_conv_vgg https://github.com/warmspringwinds/models`

**Comment by ahundt** [comment]
turns out I'm not using that model, so not needed. Though I think one of the other branches in the repository referenced does work.
